"""epic 1 assessment platform tables

Revision ID: 31e137d01f8f
Revises: 55edff3f7e8a
Create Date: 2026-07-23 12:21:35.014139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31e137d01f8f'
down_revision: Union[str, None] = '55edff3f7e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_activity',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_date', sa.String(length=20), nullable=False),
    sa.Column('study_time_seconds', sa.Integer(), nullable=False),
    sa.Column('questions_solved', sa.Integer(), nullable=False),
    sa.Column('tests_taken', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_activity_activity_date'), 'daily_activity', ['activity_date'], unique=False)
    op.create_index(op.f('ix_daily_activity_is_deleted'), 'daily_activity', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_daily_activity_user_id'), 'daily_activity', ['user_id'], unique=False)
    op.create_table('study_statistics',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_questions_attempted', sa.Integer(), nullable=False),
    sa.Column('overall_accuracy_pct', sa.Float(), nullable=False),
    sa.Column('current_streak_days', sa.Integer(), nullable=False),
    sa.Column('longest_streak_days', sa.Integer(), nullable=False),
    sa.Column('learning_health_score', sa.Float(), nullable=False),
    sa.Column('retention_pct', sa.Float(), nullable=False),
    sa.Column('subject_accuracy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_statistics_is_deleted'), 'study_statistics', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_study_statistics_user_id'), 'study_statistics', ['user_id'], unique=True)
    op.create_table('leaderboard',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=True),
    sa.Column('mock_test_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('percentile', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mock_test_id'], ['mock_tests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_exam_id'), 'leaderboard', ['exam_id'], unique=False)
    op.create_index(op.f('ix_leaderboard_is_deleted'), 'leaderboard', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_leaderboard_mock_test_id'), 'leaderboard', ['mock_test_id'], unique=False)
    op.create_index(op.f('ix_leaderboard_period'), 'leaderboard', ['period'], unique=False)
    op.create_index(op.f('ix_leaderboard_user_id'), 'leaderboard', ['user_id'], unique=False)
    op.create_table('practice_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.Enum('LEARNING', 'PRACTICE', 'TIMED_PRACTICE', 'EXAM_SIMULATION', 'REVISION', 'WEAK_TOPIC_PRACTICE', 'BOOKMARKED_QUESTIONS', 'PREVIOUS_YEAR_PRACTICE', 'DAILY_CHALLENGE', 'MARATHON', name='learningmode'), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', 'PAUSED', name='attemptstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sessions_is_deleted'), 'practice_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_practice_sessions_mode'), 'practice_sessions', ['mode'], unique=False)
    op.create_index(op.f('ix_practice_sessions_status'), 'practice_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_practice_sessions_subject_id'), 'practice_sessions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_topic_id'), 'practice_sessions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_user_id'), 'practice_sessions', ['user_id'], unique=False)
    op.create_table('attempts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mock_test_id', sa.UUID(), nullable=True),
    sa.Column('practice_session_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.Enum('LEARNING', 'PRACTICE', 'TIMED_PRACTICE', 'EXAM_SIMULATION', 'REVISION', 'WEAK_TOPIC_PRACTICE', 'BOOKMARKED_QUESTIONS', 'PREVIOUS_YEAR_PRACTICE', 'DAILY_CHALLENGE', 'MARATHON', name='learningmode'), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', 'PAUSED', name='attemptstatus'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('accuracy_pct', sa.Float(), nullable=False),
    sa.Column('speed_seconds_per_q', sa.Float(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('client_sync_id', sa.String(length=100), nullable=True),
    sa.Column('ai_learning_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mock_test_id'], ['mock_tests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_client_sync_id'), 'attempts', ['client_sync_id'], unique=False)
    op.create_index(op.f('ix_attempts_is_deleted'), 'attempts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_attempts_mock_test_id'), 'attempts', ['mock_test_id'], unique=False)
    op.create_index(op.f('ix_attempts_mode'), 'attempts', ['mode'], unique=False)
    op.create_index(op.f('ix_attempts_practice_session_id'), 'attempts', ['practice_session_id'], unique=False)
    op.create_index(op.f('ix_attempts_status'), 'attempts', ['status'], unique=False)
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    op.create_table('exam_results',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=True),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('percentile', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('strengths_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_results_attempt_id'), 'exam_results', ['attempt_id'], unique=True)
    op.create_index(op.f('ix_exam_results_exam_id'), 'exam_results', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_results_is_deleted'), 'exam_results', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_exam_results_user_id'), 'exam_results', ['user_id'], unique=False)
    op.create_table('question_mastery',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_ATTEMPTED', 'CORRECT_ONCE', 'CORRECT_MULTIPLE', 'INCORRECT', 'NEEDS_REVISION', 'MASTERED', 'BOOKMARKED', name='questionmasterystatus'), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('times_incorrect', sa.Integer(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_mastery_is_deleted'), 'question_mastery', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_question_mastery_question_id'), 'question_mastery', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_mastery_status'), 'question_mastery', ['status'], unique=False)
    op.create_index(op.f('ix_question_mastery_user_id'), 'question_mastery', ['user_id'], unique=False)
    op.create_table('revision_queue',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('easiness_factor', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revision_queue_is_deleted'), 'revision_queue', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_revision_queue_question_id'), 'revision_queue', ['question_id'], unique=False)
    op.create_index(op.f('ix_revision_queue_scheduled_for'), 'revision_queue', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_revision_queue_user_id'), 'revision_queue', ['user_id'], unique=False)
    op.create_table('attempt_questions',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_id', sa.UUID(), nullable=True),
    sa.Column('user_answer_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UNVISITED', 'VISITED', 'ANSWERED', 'MARKED_FOR_REVIEW', 'ANSWERED_AND_MARKED', name='attemptquestionstatus'), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_questions_attempt_id'), 'attempt_questions', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_attempt_questions_is_deleted'), 'attempt_questions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_attempt_questions_question_id'), 'attempt_questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_attempt_questions_status'), 'attempt_questions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempt_questions_status'), table_name='attempt_questions')
    op.drop_index(op.f('ix_attempt_questions_question_id'), table_name='attempt_questions')
    op.drop_index(op.f('ix_attempt_questions_is_deleted'), table_name='attempt_questions')
    op.drop_index(op.f('ix_attempt_questions_attempt_id'), table_name='attempt_questions')
    op.drop_table('attempt_questions')
    op.drop_index(op.f('ix_revision_queue_user_id'), table_name='revision_queue')
    op.drop_index(op.f('ix_revision_queue_scheduled_for'), table_name='revision_queue')
    op.drop_index(op.f('ix_revision_queue_question_id'), table_name='revision_queue')
    op.drop_index(op.f('ix_revision_queue_is_deleted'), table_name='revision_queue')
    op.drop_table('revision_queue')
    op.drop_index(op.f('ix_question_mastery_user_id'), table_name='question_mastery')
    op.drop_index(op.f('ix_question_mastery_status'), table_name='question_mastery')
    op.drop_index(op.f('ix_question_mastery_question_id'), table_name='question_mastery')
    op.drop_index(op.f('ix_question_mastery_is_deleted'), table_name='question_mastery')
    op.drop_table('question_mastery')
    op.drop_index(op.f('ix_exam_results_user_id'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_is_deleted'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_exam_id'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_attempt_id'), table_name='exam_results')
    op.drop_table('exam_results')
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_status'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_practice_session_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_mode'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_mock_test_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_is_deleted'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_client_sync_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_practice_sessions_user_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_topic_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_subject_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_status'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_mode'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_is_deleted'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    op.drop_index(op.f('ix_leaderboard_user_id'), table_name='leaderboard')
    op.drop_index(op.f('ix_leaderboard_period'), table_name='leaderboard')
    op.drop_index(op.f('ix_leaderboard_mock_test_id'), table_name='leaderboard')
    op.drop_index(op.f('ix_leaderboard_is_deleted'), table_name='leaderboard')
    op.drop_index(op.f('ix_leaderboard_exam_id'), table_name='leaderboard')
    op.drop_table('leaderboard')
    op.drop_index(op.f('ix_study_statistics_user_id'), table_name='study_statistics')
    op.drop_index(op.f('ix_study_statistics_is_deleted'), table_name='study_statistics')
    op.drop_table('study_statistics')
    op.drop_index(op.f('ix_daily_activity_user_id'), table_name='daily_activity')
    op.drop_index(op.f('ix_daily_activity_is_deleted'), table_name='daily_activity')
    op.drop_index(op.f('ix_daily_activity_activity_date'), table_name='daily_activity')
    op.drop_table('daily_activity')
    # ### end Alembic commands ###
