"""milestone 7 question intelligence platform

Revision ID: 55edff3f7e8a
Revises: de86b2506378
Create Date: 2026-07-23 12:13:36.905640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55edff3f7e8a'
down_revision: Union[str, None] = 'de86b2506378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bloom_taxonomy_enum = sa.Enum('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE', name='bloomtaxonomy')
    bloom_taxonomy_enum.create(op.get_bind(), checkfirst=True)
    
    question_status_enum = sa.Enum('DRAFT', 'SUBMITTED', 'REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'PUBLISHED', 'RETIRED', 'ARCHIVED', name='questionstatus')
    question_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('learning_objectives',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('bloom_level', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_objectives_code'), 'learning_objectives', ['code'], unique=True)
    op.create_index(op.f('ix_learning_objectives_is_deleted'), 'learning_objectives', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_learning_objectives_topic_id'), 'learning_objectives', ['topic_id'], unique=False)
    op.create_table('subtopics',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtopics_is_deleted'), 'subtopics', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_subtopics_name'), 'subtopics', ['name'], unique=False)
    op.create_index(op.f('ix_subtopics_topic_id'), 'subtopics', ['topic_id'], unique=False)
    op.create_table('question_audit_logs',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('performed_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_audit_logs_is_deleted'), 'question_audit_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_question_audit_logs_question_id'), 'question_audit_logs', ['question_id'], unique=False)
    op.create_table('question_relations',
    sa.Column('source_question_id', sa.UUID(), nullable=False),
    sa.Column('target_question_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_relations_is_deleted'), 'question_relations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_question_relations_source_question_id'), 'question_relations', ['source_question_id'], unique=False)
    op.create_index(op.f('ix_question_relations_target_question_id'), 'question_relations', ['target_question_id'], unique=False)
    op.create_table('question_reports',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_reports_is_deleted'), 'question_reports', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_question_reports_question_id'), 'question_reports', ['question_id'], unique=False)
    op.create_table('question_revisions',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_revisions_is_deleted'), 'question_revisions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_question_revisions_question_id'), 'question_revisions', ['question_id'], unique=False)
    op.add_column('question_options', sa.Column('option_index', sa.Integer(), nullable=False))
    op.add_column('question_options', sa.Column('explanation', sa.Text(), nullable=True))
    op.alter_column('question_options', 'content',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('questions', sa.Column('subject_id', sa.UUID(), nullable=True))
    op.add_column('questions', sa.Column('chapter_id', sa.UUID(), nullable=True))
    op.add_column('questions', sa.Column('subtopic_id', sa.UUID(), nullable=True))
    op.add_column('questions', sa.Column('learning_objective_id', sa.UUID(), nullable=True))
    op.add_column('questions', sa.Column('bloom_taxonomy', sa.Enum('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE', name='bloomtaxonomy'), nullable=True))
    op.add_column('questions', sa.Column('marks', sa.Float(), nullable=False))
    op.add_column('questions', sa.Column('negative_marks', sa.Float(), nullable=False))
    op.add_column('questions', sa.Column('language', sa.String(length=50), nullable=False))
    op.add_column('questions', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('questions', sa.Column('reference_book', sa.String(length=255), nullable=True))
    op.add_column('questions', sa.Column('estimated_time_seconds', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'PUBLISHED', 'RETIRED', 'ARCHIVED', name='questionstatus'), nullable=False))
    op.add_column('questions', sa.Column('verification_status', sa.String(length=50), nullable=False))
    op.add_column('questions', sa.Column('creation_source', sa.String(length=50), nullable=False))
    op.add_column('questions', sa.Column('author_id', sa.UUID(), nullable=True))
    op.add_column('questions', sa.Column('detailed_explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('quick_trick_explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('video_explanation_url', sa.String(length=500), nullable=True))
    op.add_column('questions', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('analytics_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('questions', 'topic_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_questions_author_id'), 'questions', ['author_id'], unique=False)
    op.create_index(op.f('ix_questions_bloom_taxonomy'), 'questions', ['bloom_taxonomy'], unique=False)
    op.create_index(op.f('ix_questions_chapter_id'), 'questions', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_questions_creation_source'), 'questions', ['creation_source'], unique=False)
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_language'), 'questions', ['language'], unique=False)
    op.create_index(op.f('ix_questions_learning_objective_id'), 'questions', ['learning_objective_id'], unique=False)
    op.create_index(op.f('ix_questions_question_type'), 'questions', ['question_type'], unique=False)
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    op.create_index(op.f('ix_questions_subject_id'), 'questions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_questions_subtopic_id'), 'questions', ['subtopic_id'], unique=False)
    op.create_index(op.f('ix_questions_verification_status'), 'questions', ['verification_status'], unique=False)
    op.create_foreign_key(None, 'questions', 'subtopics', ['subtopic_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'questions', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'questions', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'questions', 'chapters', ['chapter_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'questions', 'learning_objectives', ['learning_objective_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_verification_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_subtopic_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_subject_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_question_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_learning_objective_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_language'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_index(op.f('ix_questions_creation_source'), table_name='questions')
    op.drop_index(op.f('ix_questions_chapter_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_bloom_taxonomy'), table_name='questions')
    op.drop_index(op.f('ix_questions_author_id'), table_name='questions')
    op.alter_column('questions', 'topic_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('questions', 'analytics_summary')
    op.drop_column('questions', 'ai_metadata')
    op.drop_column('questions', 'tags')
    op.drop_column('questions', 'video_explanation_url')
    op.drop_column('questions', 'quick_trick_explanation')
    op.drop_column('questions', 'detailed_explanation')
    op.drop_column('questions', 'author_id')
    op.drop_column('questions', 'creation_source')
    op.drop_column('questions', 'verification_status')
    op.drop_column('questions', 'status')
    op.drop_column('questions', 'estimated_time_seconds')
    op.drop_column('questions', 'reference_book')
    op.drop_column('questions', 'source')
    op.drop_column('questions', 'language')
    op.drop_column('questions', 'negative_marks')
    op.drop_column('questions', 'marks')
    op.drop_column('questions', 'bloom_taxonomy')
    op.drop_column('questions', 'learning_objective_id')
    op.drop_column('questions', 'subtopic_id')
    op.drop_column('questions', 'chapter_id')
    op.drop_column('questions', 'subject_id')
    op.alter_column('question_options', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('question_options', 'explanation')
    op.drop_column('question_options', 'option_index')
    op.drop_index(op.f('ix_question_revisions_question_id'), table_name='question_revisions')
    op.drop_index(op.f('ix_question_revisions_is_deleted'), table_name='question_revisions')
    op.drop_table('question_revisions')
    op.drop_index(op.f('ix_question_reports_question_id'), table_name='question_reports')
    op.drop_index(op.f('ix_question_reports_is_deleted'), table_name='question_reports')
    op.drop_table('question_reports')
    op.drop_index(op.f('ix_question_relations_target_question_id'), table_name='question_relations')
    op.drop_index(op.f('ix_question_relations_source_question_id'), table_name='question_relations')
    op.drop_index(op.f('ix_question_relations_is_deleted'), table_name='question_relations')
    op.drop_table('question_relations')
    op.drop_index(op.f('ix_question_audit_logs_question_id'), table_name='question_audit_logs')
    op.drop_index(op.f('ix_question_audit_logs_is_deleted'), table_name='question_audit_logs')
    op.drop_table('question_audit_logs')
    op.drop_index(op.f('ix_subtopics_topic_id'), table_name='subtopics')
    op.drop_index(op.f('ix_subtopics_name'), table_name='subtopics')
    op.drop_index(op.f('ix_subtopics_is_deleted'), table_name='subtopics')
    op.drop_table('subtopics')
    op.drop_index(op.f('ix_learning_objectives_topic_id'), table_name='learning_objectives')
    op.drop_index(op.f('ix_learning_objectives_is_deleted'), table_name='learning_objectives')
    op.drop_index(op.f('ix_learning_objectives_code'), table_name='learning_objectives')
    op.drop_table('learning_objectives')
    # ### end Alembic commands ###
