"""milestone 6 cms

Revision ID: de86b2506378
Revises: 99eb9d3a0ff7
Create Date: 2026-07-22 18:05:57.837734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de86b2506378'
down_revision: Union[str, None] = '99eb9d3a0ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('BOOK', 'VIDEO', 'NOTE', 'PDF', 'MIND_MAP', 'FLASH_CARD', 'FORMULA_SHEET', 'QUESTION_BANK', 'CURRENT_AFFAIR', 'PREVIOUS_PAPER', 'MOCK_TEST', name='contenttype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('publish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_author_id'), 'content_items', ['author_id'], unique=False)
    op.create_index(op.f('ix_content_items_content_type'), 'content_items', ['content_type'], unique=False)
    op.create_index(op.f('ix_content_items_expiry_date'), 'content_items', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_content_items_is_deleted'), 'content_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_content_items_publish_date'), 'content_items', ['publish_date'], unique=False)
    op.create_index(op.f('ix_content_items_slug'), 'content_items', ['slug'], unique=True)
    op.create_index(op.f('ix_content_items_status'), 'content_items', ['status'], unique=False)
    op.create_index(op.f('ix_content_items_title'), 'content_items', ['title'], unique=False)
    op.create_table('content_audit_logs',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('performed_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_audit_logs_content_item_id'), 'content_audit_logs', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_content_audit_logs_is_deleted'), 'content_audit_logs', ['is_deleted'], unique=False)
    op.create_table('content_book_details',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('isbn', sa.String(length=50), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_book_details_content_item_id'), 'content_book_details', ['content_item_id'], unique=True)
    op.create_index(op.f('ix_content_book_details_is_deleted'), 'content_book_details', ['is_deleted'], unique=False)
    op.create_table('content_flashcard_details',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('deck_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_flashcard_details_content_item_id'), 'content_flashcard_details', ['content_item_id'], unique=True)
    op.create_index(op.f('ix_content_flashcard_details_is_deleted'), 'content_flashcard_details', ['is_deleted'], unique=False)
    op.create_table('content_mindmap_details',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('interactive_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_mindmap_details_content_item_id'), 'content_mindmap_details', ['content_item_id'], unique=True)
    op.create_index(op.f('ix_content_mindmap_details_is_deleted'), 'content_mindmap_details', ['is_deleted'], unique=False)
    op.create_table('content_pdf_details',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_pdf_details_content_item_id'), 'content_pdf_details', ['content_item_id'], unique=True)
    op.create_index(op.f('ix_content_pdf_details_is_deleted'), 'content_pdf_details', ['is_deleted'], unique=False)
    op.create_table('content_quiz_details',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('passing_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_quiz_details_content_item_id'), 'content_quiz_details', ['content_item_id'], unique=True)
    op.create_index(op.f('ix_content_quiz_details_is_deleted'), 'content_quiz_details', ['is_deleted'], unique=False)
    op.create_table('content_revisions',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_revisions_content_item_id'), 'content_revisions', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_content_revisions_is_deleted'), 'content_revisions', ['is_deleted'], unique=False)
    op.create_table('content_video_details',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_video_details_content_item_id'), 'content_video_details', ['content_item_id'], unique=True)
    op.create_index(op.f('ix_content_video_details_is_deleted'), 'content_video_details', ['is_deleted'], unique=False)
    op.drop_constraint('resources_note_id_fkey', 'resources', type_='foreignkey')
    op.drop_constraint('resources_book_id_fkey', 'resources', type_='foreignkey')
    op.drop_constraint('resources_video_id_fkey', 'resources', type_='foreignkey')
    op.drop_constraint('exam_current_affairs_current_affair_id_fkey', 'exam_current_affairs', type_='foreignkey')

    op.drop_index(op.f('ix_books_is_deleted'), table_name='books')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_videos_is_deleted'), table_name='videos')
    op.drop_index(op.f('ix_videos_title'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_current_affairs_is_deleted'), table_name='current_affairs')
    op.drop_index(op.f('ix_current_affairs_publish_date'), table_name='current_affairs')
    op.drop_index(op.f('ix_current_affairs_title'), table_name='current_affairs')
    op.drop_table('current_affairs')
    op.drop_index(op.f('ix_notes_is_deleted'), table_name='notes')
    op.drop_index(op.f('ix_notes_title'), table_name='notes')
    op.drop_table('notes')
    op.add_column('exam_current_affairs', sa.Column('content_item_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_exam_current_affairs_current_affair_id'), table_name='exam_current_affairs')
    op.create_index(op.f('ix_exam_current_affairs_content_item_id'), 'exam_current_affairs', ['content_item_id'], unique=False)
    op.create_foreign_key(None, 'exam_current_affairs', 'content_items', ['content_item_id'], ['id'], ondelete='CASCADE')
    op.drop_column('exam_current_affairs', 'current_affair_id')
    op.add_column('resources', sa.Column('content_item_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_resources_book_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_note_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_title'), table_name='resources')
    op.drop_index(op.f('ix_resources_video_id'), table_name='resources')
    op.create_index(op.f('ix_resources_content_item_id'), 'resources', ['content_item_id'], unique=False)
    op.create_foreign_key(None, 'resources', 'content_items', ['content_item_id'], ['id'], ondelete='CASCADE')
    op.drop_column('resources', 'description')
    op.drop_column('resources', 'video_id')
    op.drop_column('resources', 'note_id')
    op.drop_column('resources', 'book_id')
    op.drop_column('resources', 'resource_type')
    op.drop_column('resources', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('resources', sa.Column('resource_type', postgresql.ENUM('VIDEO', 'BOOK', 'NOTE', name='resourcetype'), autoincrement=False, nullable=False))
    op.add_column('resources', sa.Column('book_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('resources', sa.Column('note_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('resources', sa.Column('video_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('resources', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.create_foreign_key(op.f('resources_video_id_fkey'), 'resources', 'videos', ['video_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('resources_book_id_fkey'), 'resources', 'books', ['book_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('resources_note_id_fkey'), 'resources', 'notes', ['note_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_resources_content_item_id'), table_name='resources')
    op.create_index(op.f('ix_resources_video_id'), 'resources', ['video_id'], unique=False)
    op.create_index(op.f('ix_resources_title'), 'resources', ['title'], unique=False)
    op.create_index(op.f('ix_resources_note_id'), 'resources', ['note_id'], unique=False)
    op.create_index(op.f('ix_resources_book_id'), 'resources', ['book_id'], unique=False)
    op.drop_column('resources', 'content_item_id')
    op.add_column('exam_current_affairs', sa.Column('current_affair_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exam_current_affairs', type_='foreignkey')
    op.create_foreign_key(op.f('exam_current_affairs_current_affair_id_fkey'), 'exam_current_affairs', 'current_affairs', ['current_affair_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_exam_current_affairs_content_item_id'), table_name='exam_current_affairs')
    op.create_index(op.f('ix_exam_current_affairs_current_affair_id'), 'exam_current_affairs', ['current_affair_id'], unique=False)
    op.drop_column('exam_current_affairs', 'content_item_id')
    op.create_table('notes',
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('notes_pkey'))
    )
    op.create_index(op.f('ix_notes_title'), 'notes', ['title'], unique=False)
    op.create_index(op.f('ix_notes_is_deleted'), 'notes', ['is_deleted'], unique=False)
    op.create_table('current_affairs',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('publish_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('current_affairs_pkey'))
    )
    op.create_index(op.f('ix_current_affairs_title'), 'current_affairs', ['title'], unique=False)
    op.create_index(op.f('ix_current_affairs_publish_date'), 'current_affairs', ['publish_date'], unique=False)
    op.create_index(op.f('ix_current_affairs_is_deleted'), 'current_affairs', ['is_deleted'], unique=False)
    op.create_table('videos',
    sa.Column('video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('videos_pkey'))
    )
    op.create_index(op.f('ix_videos_title'), 'videos', ['title'], unique=False)
    op.create_index(op.f('ix_videos_is_deleted'), 'videos', ['is_deleted'], unique=False)
    op.create_table('books',
    sa.Column('author', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('pdf_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('books_pkey'))
    )
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_index(op.f('ix_books_is_deleted'), 'books', ['is_deleted'], unique=False)
    op.drop_index(op.f('ix_content_video_details_is_deleted'), table_name='content_video_details')
    op.drop_index(op.f('ix_content_video_details_content_item_id'), table_name='content_video_details')
    op.drop_table('content_video_details')
    op.drop_index(op.f('ix_content_revisions_is_deleted'), table_name='content_revisions')
    op.drop_index(op.f('ix_content_revisions_content_item_id'), table_name='content_revisions')
    op.drop_table('content_revisions')
    op.drop_index(op.f('ix_content_quiz_details_is_deleted'), table_name='content_quiz_details')
    op.drop_index(op.f('ix_content_quiz_details_content_item_id'), table_name='content_quiz_details')
    op.drop_table('content_quiz_details')
    op.drop_index(op.f('ix_content_pdf_details_is_deleted'), table_name='content_pdf_details')
    op.drop_index(op.f('ix_content_pdf_details_content_item_id'), table_name='content_pdf_details')
    op.drop_table('content_pdf_details')
    op.drop_index(op.f('ix_content_mindmap_details_is_deleted'), table_name='content_mindmap_details')
    op.drop_index(op.f('ix_content_mindmap_details_content_item_id'), table_name='content_mindmap_details')
    op.drop_table('content_mindmap_details')
    op.drop_index(op.f('ix_content_flashcard_details_is_deleted'), table_name='content_flashcard_details')
    op.drop_index(op.f('ix_content_flashcard_details_content_item_id'), table_name='content_flashcard_details')
    op.drop_table('content_flashcard_details')
    op.drop_index(op.f('ix_content_book_details_is_deleted'), table_name='content_book_details')
    op.drop_index(op.f('ix_content_book_details_content_item_id'), table_name='content_book_details')
    op.drop_table('content_book_details')
    op.drop_index(op.f('ix_content_audit_logs_is_deleted'), table_name='content_audit_logs')
    op.drop_index(op.f('ix_content_audit_logs_content_item_id'), table_name='content_audit_logs')
    op.drop_table('content_audit_logs')
    op.drop_index(op.f('ix_content_items_title'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_status'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_slug'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_publish_date'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_is_deleted'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_expiry_date'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_content_type'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_author_id'), table_name='content_items')
    op.drop_table('content_items')
    # ### end Alembic commands ###
